title: happylittleboy.top
email: damonyang.littleboy@gmail.com
description: " on the way "
baseurl: "happylittleboy.top"
url: "http://happylittleboy.top" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  happlittleboy

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
